# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Steganography(object):
    def setupUi(self, Steganography):
        Steganography.setObjectName("Steganography")
        Steganography.resize(854, 590)
        self.centralwidget = QtWidgets.QWidget(Steganography)
        self.centralwidget.setObjectName("centralwidget")
        self.imgButton = QtWidgets.QPushButton(self.centralwidget)
        self.imgButton.setGeometry(QtCore.QRect(10, 470, 151, 41))
        self.imgButton.setObjectName("imgButton")
        self.encButton = QtWidgets.QPushButton(self.centralwidget)
        self.encButton.setGeometry(QtCore.QRect(10, 140, 151, 41))
        self.encButton.setObjectName("encButton")
        self.secretKeyInput = QtWidgets.QLineEdit(self.centralwidget)
        self.secretKeyInput.setGeometry(QtCore.QRect(10, 80, 151, 41))
        self.secretKeyInput.setObjectName("secretKeyInput")
        self.secretKeyLabel = QtWidgets.QLabel(self.centralwidget)
        self.secretKeyLabel.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.secretKeyLabel.setObjectName("secretKeyLabel")
        self.decButton = QtWidgets.QPushButton(self.centralwidget)
        self.decButton.setGeometry(QtCore.QRect(10, 190, 151, 41))
        self.decButton.setObjectName("decButton")
        self.textLabel = QtWidgets.QLabel(self.centralwidget)
        self.textLabel.setGeometry(QtCore.QRect(176, 242, 51, 31))
        self.textLabel.setObjectName("textLabel")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(170, 280, 671, 281))
        self.textEdit.setObjectName("textEdit")
        self.fileLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileLabel.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.fileLabel.setText("")
        self.fileLabel.setObjectName("fileLabel")
        self.imgLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel2.setGeometry(QtCore.QRect(510, 10, 331, 221))
        self.imgLabel2.setText("")
        self.imgLabel2.setObjectName("imgLabel2")
        self.imgLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel1.setGeometry(QtCore.QRect(170, 10, 331, 221))
        self.imgLabel1.setText("")
        self.imgLabel1.setObjectName("imgLabel1")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(10, 520, 151, 41))
        self.downloadButton.setObjectName("downloadButton")
        Steganography.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Steganography)
        self.statusbar.setObjectName("statusbar")
        Steganography.setStatusBar(self.statusbar)

        self.retranslateUi(Steganography)
        QtCore.QMetaObject.connectSlotsByName(Steganography)

    def retranslateUi(self, Steganography):
        _translate = QtCore.QCoreApplication.translate
        Steganography.setWindowTitle(_translate("Steganography", "Steganography"))
        self.imgButton.setText(_translate("Steganography", "Upload Image"))
        self.encButton.setText(_translate("Steganography", "Encript Image"))
        self.secretKeyLabel.setText(_translate("Steganography", "Secret Key:"))
        self.decButton.setText(_translate("Steganography", "Decrypt Image"))
        self.textLabel.setText(_translate("Steganography", "Text:"))
        self.downloadButton.setText(_translate("Steganography", "Download Image"))
